### ISSUE TITLE
Translate the About page.

### ISSUE THREAD

**Issue by andre-carvalho** [andre-carvalho/PRODESdashboard#35]

**Comment by jether2011** [comment]
@luizassis @andre-carvalho 
Informações enviadas pela Karine em 16/11/2017 para alteração:

- (1) Em "Visão", podemo colocar assim somente esse texto:

`O TerraBrasilis é uma plataforma desenvolvida pelo INPE para organização, acesso e uso através de um portal web dos dados geográficos produzidos pelos seus programas de monitoramento ambiental. Em um primeiro momento visa atender principalmente ao Programa Amazônia, mas o conceito e os pacotes de software produzidos podem ser adaptados e customizados para atender a outros projetos que produzam dados geográficos e que pretendem que esses possam ser acessados no ambiente da internet.`

Mais informações sobre o TerraBrasilis, veja em: http://terrabrasilis.info/

- (2) Em "Apoio", adicionar o BNDES e o Banco Mundial

- (3) Por favor, façam uma revisão do site: http://terrabrasilis.info/
